{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
stringData:
  SERVER_HOST: {{ required (print "Please enter server host") .Values.secret.server_host }}
  SERVER_PORT: {{ required (print "Please enter server port") .Values.secret.server_port | quote }}
  DB_HOST: {{ required (print "Please enter Postgresql DB host") .Values.secret.db_host }}
  DB_USER: {{ required (print "Please enter Postgresql DB user") .Values.secret.db_user }}
  DB_PASSWORD: {{ required (print "Please enter Postgresql DB password") .Values.secret.db_password }}
  DB_NAME: {{ required (print "Please enter Postgresql DB bane") .Values.secret.db_name }}
  REDIS_HOST: {{ required (print "Please enter Redis host") .Values.secret.redis_host }}
  REDIS_PORT: {{ required (print "Please enter Redis port") .Values.secret.redis_port | quote }}
  REDIS_PREFIX: {{ required (print "Please enter Redis prefix") .Values.secret.redis_prefix }}
{{- end }}
